// <auto-generated />
using System;
using JobHunter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHunter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobHunterDbContext))]
    [Migration("20260916142928_AiAnalysisRevisionIdentity")]
    partial class AiAnalysisRevisionIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JobHunter.Domain.AI.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileSnapshotId");

                    b.HasIndex("JobId", "CandidateProfileSnapshotId", "JobRevisionNumber", "Provider", "SchemaVersion", "RubricVersion")
                        .IsUnique();

                    b.ToTable("AiAnalyses", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Evaluation.RuleEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissingDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PassedHardFilters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RubricVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesAndAiThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesOnlyThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileSnapshotId");

                    b.HasIndex("JobId", "CandidateProfileSnapshotId", "JobRevisionNumber", "RubricVersion")
                        .IsUnique();

                    b.ToTable("RuleEvaluations", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompensationCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CompensationMaximum")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CompensationMinimum")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompensationPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("FingerprintVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedAtPrecision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkplaceMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("Source", "CanonicalUrl")
                        .IsUnique()
                        .HasFilter("\"SourceJobId\" IS NULL");

                    b.HasIndex("Source", "SourceJobId")
                        .IsUnique()
                        .HasFilter("\"SourceJobId\" IS NOT NULL");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayloadHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGuid")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SourceSubscriptionId");

                    b.HasIndex("SourceRunId", "JobId", "RawPayloadHash")
                        .IsUnique();

                    b.ToTable("JobObservations", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobPossibleDuplicate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FirstJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecondJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SecondJobId");

                    b.HasIndex("FirstJobId", "SecondJobId")
                        .IsUnique();

                    b.ToTable("JobPossibleDuplicates", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("JobRevisions", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Notifications.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotificationOutboxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotificationOutboxId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("DeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Notifications.NotificationDestinationState", b =>
                {
                    b.Property<string>("DestinationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("DestinationId");

                    b.ToTable("NotificationDestinationStates", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Notifications.NotificationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("DestinationId", "JobId", "NotificationVersion")
                        .IsUnique();

                    b.ToTable("NotificationOutbox", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Operations.ApplicationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ApplicationEvents", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Profiles.CandidateProfileSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplementalCvRedacted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("ProfileVersion")
                        .IsUnique();

                    b.ToTable("CandidateProfiles", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceCursor", b =>
                {
                    b.Property<Guid>("SourceSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTag")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpaqueValue")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceSubscriptionId");

                    b.ToTable("SourceCursors", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CursorJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("HeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RetryAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSubscriptionId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("SourceSubscriptionId", "StartedAtUtc");

                    b.ToTable("SourceRuns", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BackoffUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSucceededAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextDueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDiagnostic")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SubscriptionKey")
                        .IsUnique();

                    b.ToTable("SourceSubscriptions", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.AI.AiAnalysis", b =>
                {
                    b.HasOne("JobHunter.Domain.Profiles.CandidateProfileSnapshot", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Evaluation.RuleEvaluation", b =>
                {
                    b.HasOne("JobHunter.Domain.Profiles.CandidateProfileSnapshot", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobObservation", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", "Job")
                        .WithMany("Observations")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Sources.SourceRun", "SourceRun")
                        .WithMany("Observations")
                        .HasForeignKey("SourceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Sources.SourceSubscription", null)
                        .WithMany()
                        .HasForeignKey("SourceSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("SourceRun");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobPossibleDuplicate", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", "FirstJob")
                        .WithMany()
                        .HasForeignKey("FirstJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", "SecondJob")
                        .WithMany()
                        .HasForeignKey("SecondJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstJob");

                    b.Navigation("SecondJob");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobRevision", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", "Job")
                        .WithMany("Revisions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobHunter.Domain.Notifications.DeliveryAttempt", b =>
                {
                    b.HasOne("JobHunter.Domain.Notifications.NotificationOutbox", "NotificationOutbox")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationOutboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationOutbox");
                });

            modelBuilder.Entity("JobHunter.Domain.Notifications.NotificationOutbox", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceCursor", b =>
                {
                    b.HasOne("JobHunter.Domain.Sources.SourceSubscription", "SourceSubscription")
                        .WithOne("Cursor")
                        .HasForeignKey("JobHunter.Domain.Sources.SourceCursor", "SourceSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSubscription");
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceRun", b =>
                {
                    b.HasOne("JobHunter.Domain.Sources.SourceSubscription", "SourceSubscription")
                        .WithMany("Runs")
                        .HasForeignKey("SourceSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSubscription");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("JobHunter.Domain.Notifications.NotificationOutbox", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceRun", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceSubscription", b =>
                {
                    b.Navigation("Cursor");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
